package client_api

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"strings"
)

var (
	METHOD = "POST"
)

type Topic struct {
	Model       string    `json:"model"`
	Temperature float64   `json:"temperature"`
	Messages    []Message `json:"messages"`
}
type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type AutoGenerated struct {
	ID      string   `json:"id"`
	Object  string   `json:"object"`
	Created int64    `json:"created"`
	Model   string   `json:"model"`
	Usage   Usage    `json:"usage"`
	Choices []Choice `json:"choices"`
}

type Choice struct {
	Message      Message `json:"message"`
	FinishReason string  `json:"finish_reason"`
	Index        int64   `json:"index"`
}

type Usage struct {
	PromptTokens     int64 `json:"prompt_tokens"`
	CompletionTokens int64 `json:"completion_tokens"`
	TotalTokens      int64 `json:"total_tokens"`
}

func Ask(payload Topic) []Choice {
	client := &http.Client{}
	Payload, _ := json.Marshal(payload)
	str := strings.NewReader(string(Payload))
	req, err := http.NewRequest(METHOD, os.Getenv("CHATGPT_API"), str)
	if err != nil {
		fmt.Println(err)
	}

	req.Header.Add("Content-Type", "application/json")
	req.Header.Add("Authorization", os.Getenv("CHATGPT_TOKEN"))
	req.Header.Add("OpenAI-Organization", os.Getenv("ORGANIZATION"))

	res, err := client.Do(req)
	if err != nil {
		fmt.Println(err)
	}
	defer res.Body.Close()
	body, err := ioutil.ReadAll(res.Body)
	if err != nil {
		fmt.Println(err)
		return []Choice{}
	}

	topic := AutoGenerated{}

	if err = json.Unmarshal(body, &topic); err != nil {
		log.Fatal("can't read data from response", err)
	}

	return topic.Choices
}
